### ISSUE TITLE
Add option for Breathing.

### ISSUE THREAD

**Issue by Ktrcoyote** [eheikes/tts-cli#35]
Polly has a new breath feature. is there a way to turn that on? https://aws.amazon.com/blogs/machine-learning/amazon-polly-releases-new-ssml-breath-feature/

**Comment by eheikes** [comment]
It looks like those are SSML tags, so you can use the [`--type ssml` option](https://github.com/eheikes/tts-cli#usage) to use those.

As an example, using the Breathless Salli XML in that blog post:

`tts breathless.xml breathless.mp3 --type ssml --voice Salli` on the Mac or Linux command line

`node .\tts.js .\breathless.xml .\breathless.mp3 --type ssml --voice Salli` on the Windows PowerShell command line

gives the same result as their embedded audio.

Hope that helps.

**Comment by Ktrcoyote** [comment]
Thanks for the reply. Again, I'm near code-illiterate so forgive me if this
sounds dumb.

The particular function i was eyeing requires bracketing the text in
something like <Autobreath>  </Autobreath>  Wouldn't I have to do it for
each 1500 characters segment to make it work?

**Comment by eheikes** [comment]
> The particular function i was eyeing requires bracketing the text in something like <Autobreath> </Autobreath> Wouldn't I have to do it for each 1500 characters segment to make it work?

I don't believe so... `tts-cli` automatically splits your text into segments, and should continue your `<auto-breath>` (and other) tags as needed. If not, feel free to open a new issue with the specific problem you're running into.
