### ISSUE TITLE
not connecting Google Cloud TTS using --service gcp option

### ISSUE THREAD

**Issue by sonodave** [eheikes/tts-cli#38]
Attempting to call the gcp service to convert a test file using google cloud tts

Win 10 machine
tts-cli works fine with AWS  version (tts-cli version1.6.0)
AWS CLI is installed and credentials are using passed using the path environment to the locally stored credentials when using tts-cli with AWS

gcloud CLI is installed   path is set to TTS project json key file for using gcp

I have a google cloud account and have downloaded the json key file. Not quite sure how to put all the pieces together so tts-cli accesses and passes the credentials to google cloud tts api. Not sure about the voice names for google cloud tts

When I try to run a test on the google cloud tts using the --service gcp option it seems to default to using the aws service and not even attempt to access the gcp api

1. What is the exact command you are running? For your security, please "X" out any AWS access keys and secrets.
tts test.txt test.mp3 --service gcp --private-key xxxxxxxxx --email xxxx@xxxx-gizmo-xxxxxxx.iam.gserviceaccount.com --project-id xxxxxxxxx --language en-US --voice Wavenet-A

2. What result are you seeing in the console? Copy & paste the exact output you get, with debugging turned on (see the [Troubleshooting section](https://github.com/eheikes/tts-cli#troubleshooting) for how to enable debugging).

 tts-cli called with arguments {"_":["test.txt","test.mp3"],"service":"gcp","private-key":"xxxxx","email":"ttsxxxxx@xxxxxxxx.iam.gserviceaccount.com","project-id":"xxxxxx","language":"en-US","voice":"Wavenet-A"} +0ms
  tts-cli input: test.txt +0ms
  tts-cli output: test.mp3 +0ms
  readText Reading from test.txt +0ms
  readText Finished reading (1273 bytes) +16ms
  chunkText Chunked into 3 text parts +0ms
  splitText Stripping whitespace +0ms
  generateSpeech Options: {"ffmpeg":"ffmpeg","format":"mp3","limit":5,"region":"us-east-1","type":"text","voice":"Wavenet-A","_":["test.txt","test.mp3"],"service":"gcp","private-key":"xxxxx","email":"xxxx@xxxxxx.iam.gserviceaccount.com","project-id":"xxxxx","language":"en-US"} +0ms
  createPolly Creating Polly instance in us-east-1 +0ms
  generateAll Requesting 3 audio segments, 5 at a time +0ms
  callAws Opening output stream to C:\Users\ElJefe\AppData\Local\Temp\844094d6-82e4-4b79-bdf1-848a8eda2555.mp3 +0ms
  callAws Making request to https://polly.us-east-1.amazonaws.com/v1/speech?OutputFormat=mp3&Text=%3Cspeak%2...&TextType=text&VoiceId=Wavenet-A&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=X-Amz-Date=20181112T153349Z&X-Amz-Expires=1800&X-Amz-Signature=8...&X-Amz-SignedHeaders=host +0ms
  callAws Opening output stream to C:\Users\ElJefe\AppData\Local\Temp\06b2f6b2-1de1-439c-9e08-b65e5b3ba3f8.mp3 +0ms
  callAws Making request to https://polly.us-east-1.amazonaws.com/v1/speech?OutputFormat=mp3&Text=And%20God%...&TextType=text&VoiceId=Wavenet-A&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...&X-Amz-Date=-Amz-Expires=1800&X-Amz-Signature=a...&X-Amz-SignedHeaders=host +0ms
  callAws Opening output stream to C:\Users\ElJefe\AppData\Local\Temp\0dbfd3de-25bf-4ce9-800c-1600ce1eea98.mp3 +0ms
  callAws Making request to https://polly.us-east-1.amazonaws.com/v1/speech?OutputFormat=mp3&Text=And%20ther...&TextType=text&VoiceId=Wavenet-A&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...&X-Amz-Date=20181112T153349Z&X-Amz-Expires=1800&X-Amz-Signature=6...&X-Amz-SignedHeaders=host +0ms
  callAws Closing output stream +0ms
  generateAll Requested all parts, with error HTTPError: Response code 400 (Bad Request) +0ms
  callAws Error during request: Response code 400 (Bad Request) +0ms
  callAws Amazon responded with {"message":"1 validation error detected: Value 'Wavenet-A' at 'voiceId' failed to satisfy constraint: Member must satisfy enum value set: [Nicole,

3. If copyright allows, please upload your input file somewhere (e.g. [pastebin](https://pastebin.com/)) and put a link to it here.

4. What OS are you using (Windows, OSX, Linux) and what version?

Windows 10

5. What version of Node.js is being used? (Run `node -v` in the console to find out.)
v10.13.0
6. What version of ffmpeg is being used? (Run `ffmpeg -version` in the console to find out.)
ffmpeg version 4.0.2

**Comment by eheikes** [comment]
Hey @sonodave, you were a little too fast -- I had to first release a new version for you could use it. :) If you install v1.7.0 or later, you should be able to use it: `npm i tts-cli@1.7.0 -g`

You can then call it with something like: `tts test.txt test.mp3 --service gcp --project-file your-project.json`. Let me know if you still run into problems!

**Comment by sonodave** [comment]
The Google Cloud TTS feature is working great. I have been waiting for this. The wavenet voices are amazing.  The only thing I don't like is google's ambiguous legal terms about use of the converted audio. They will not respond to questions and ask you to review it with your lawyer.  Amazon has been more upfront about making it clear that you are paying for a service and retain the right to use the converted audio  for any purpose and redistribution as long as you have the rights to the material being converted.
Thank you so much for your work on this!
    On Monday, November 12, 2018, 6:42:08 PM EST, Eric Heikes <notifications@github.com> wrote:  
 
 
Hey @sonodave, you were a little too fast -- I had to first release a new version for you could use it. :) If you install v1.7.0 or later, you should be able to use it: npm i tts-cli@1.7.0 -g

You can then call it with something like: tts test.txt test.mp3 --service gcp --project-file your-project.json. Let me know if you still run into problems!
