### ISSUE TITLE
Add support for  device profiles in GCP

### ISSUE THREAD

**Issue by sonodave** [eheikes/tts-cli#41]
Add support for  device profiles in GCP

**Comment by eheikes** [comment]
note to self: https://cloud.google.com/text-to-speech/docs/audio-profiles#tts-audio-profile-nodejs

**Comment by eheikes** [comment]
@sonodave I think this is already possible using the [`effect` option](https://github.com/eheikes/tts-cli/blob/master/docs/options.md#--effect), e.g.:

`tts test.txt test.mp3 --service gcp --effect handset-class-device`

Let me know if you meant something else, or if something's missing.

**Comment by sonodave** [comment]
When I read in your documentation that the effects options could be stacked I didn't think it applied to device profiles.
The command runs when I use it with -- effects without crashing but I couldn't hear any difference in the files.
I will check some more

Sent from Yahoo Mail on Android 
 
  On Sun, Mar 17, 2019 at 4:54 AM, Eric Heikes<notifications@github.com> wrote:   
@sonodave I think this is already possible using the effect option, e.g.:

tts test.txt test.mp3 --service gcp --effect handset-class-device

Let me know if you meant something else, or if something's missing.

**Comment by eheikes** [comment]
Yeah, the GCP docs say you can specify multiple profiles, but that doesn't seem very useful to me. I would stick to 1 effect myself.

**Comment by eheikes** [comment]
Re-open if there are problems.
